[2024-03-08 18:19:50 +0000] [894474] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:19:50 +0000] [894474] [INFO] Listening at: unix:/run/gunicorn.sock (894474)
[2024-03-08 18:19:50 +0000] [894474] [INFO] Using worker: sync
[2024-03-08 18:19:50 +0000] [894479] [INFO] Booting worker with pid: 894479
[2024-03-08 18:19:50 +0000] [894480] [INFO] Booting worker with pid: 894480
[2024-03-08 18:19:50 +0000] [894481] [INFO] Booting worker with pid: 894481
[2024-03-08 18:20:39,004] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 42, in blog_post
    processed_post = post_deserialized.replace("![](", "![](/images/_resources/")
AttributeError: 'dict' object has no attribute 'replace'
[2024-03-08 18:20:59,194] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 42, in blog_post
    processed_post = post_deserialized.replace("![](", "![](/images/_resources/")
AttributeError: 'dict' object has no attribute 'replace'
[2024-03-08 18:27:53 +0000] [894474] [INFO] Handling signal: term
[2024-03-08 18:27:53 +0000] [894479] [INFO] Worker exiting (pid: 894479)
[2024-03-08 18:27:53 +0000] [894480] [INFO] Worker exiting (pid: 894480)
[2024-03-08 18:27:53 +0000] [894481] [INFO] Worker exiting (pid: 894481)
[2024-03-08 18:27:53 +0000] [894474] [WARNING] Worker with pid 894479 was terminated due to signal 15
[2024-03-08 18:27:53 +0000] [894474] [INFO] Shutting down: Master
[2024-03-08 18:27:59 +0000] [894922] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:27:59 +0000] [894922] [INFO] Listening at: unix:/run/gunicorn.sock (894922)
[2024-03-08 18:27:59 +0000] [894922] [INFO] Using worker: sync
[2024-03-08 18:27:59 +0000] [894927] [INFO] Booting worker with pid: 894927
[2024-03-08 18:27:59 +0000] [894928] [INFO] Booting worker with pid: 894928
[2024-03-08 18:27:59 +0000] [894929] [INFO] Booting worker with pid: 894929
[2024-03-08 18:28:09,929] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 41, in blog_post
    post_deserialized["post_content"] = re.sub("/!\[.*\]\(", "![](", post_deserialize["post_content"])
NameError: name 'post_deserialize' is not defined
[2024-03-08 18:28:12,909] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 41, in blog_post
    post_deserialized["post_content"] = re.sub("/!\[.*\]\(", "![](", post_deserialize["post_content"])
NameError: name 'post_deserialize' is not defined
[2024-03-08 18:28:14,040] ERROR in app: Exception on /blog/blog_post/2 [GET]
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.cache/pypoetry/virtualenvs/devopsblogapp-toCHNqgA-py3.9/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ec2-user/DevOpsFlasked/DevOpsFlaskedSite/blog.py", line 41, in blog_post
    post_deserialized["post_content"] = re.sub("/!\[.*\]\(", "![](", post_deserialize["post_content"])
NameError: name 'post_deserialize' is not defined
[2024-03-08 18:29:33 +0000] [894922] [INFO] Handling signal: term
[2024-03-08 18:29:33 +0000] [894927] [INFO] Worker exiting (pid: 894927)
[2024-03-08 18:29:33 +0000] [894928] [INFO] Worker exiting (pid: 894928)
[2024-03-08 18:29:33 +0000] [894929] [INFO] Worker exiting (pid: 894929)
[2024-03-08 18:29:33 +0000] [894922] [WARNING] Worker with pid 894927 was terminated due to signal 15
[2024-03-08 18:29:33 +0000] [894922] [INFO] Shutting down: Master
[2024-03-08 18:29:39 +0000] [895038] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:29:39 +0000] [895038] [INFO] Listening at: unix:/run/gunicorn.sock (895038)
[2024-03-08 18:29:39 +0000] [895038] [INFO] Using worker: sync
[2024-03-08 18:29:39 +0000] [895043] [INFO] Booting worker with pid: 895043
[2024-03-08 18:29:39 +0000] [895044] [INFO] Booting worker with pid: 895044
[2024-03-08 18:29:39 +0000] [895045] [INFO] Booting worker with pid: 895045
[2024-03-08 18:34:18 +0000] [895038] [INFO] Handling signal: term
[2024-03-08 18:34:18 +0000] [895043] [INFO] Worker exiting (pid: 895043)
[2024-03-08 18:34:18 +0000] [895044] [INFO] Worker exiting (pid: 895044)
[2024-03-08 18:34:18 +0000] [895045] [INFO] Worker exiting (pid: 895045)
[2024-03-08 18:34:18 +0000] [895038] [WARNING] Worker with pid 895043 was terminated due to signal 15
[2024-03-08 18:34:18 +0000] [895038] [INFO] Shutting down: Master
[2024-03-08 18:34:24 +0000] [895339] [INFO] Starting gunicorn 20.1.0
[2024-03-08 18:34:24 +0000] [895339] [INFO] Listening at: unix:/run/gunicorn.sock (895339)
[2024-03-08 18:34:24 +0000] [895339] [INFO] Using worker: sync
[2024-03-08 18:34:24 +0000] [895344] [INFO] Booting worker with pid: 895344
[2024-03-08 18:34:24 +0000] [895345] [INFO] Booting worker with pid: 895345
[2024-03-08 18:34:24 +0000] [895346] [INFO] Booting worker with pid: 895346
